# Generated by Django 6.0.4 on 2026-04-20 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('semester', models.CharField(choices=[('autumn', '�������'), ('spring', '��������')], max_length=20)),
                ('ects_credits', models.PositiveIntegerField(default=3)),
                ('delivery_format', models.CharField(choices=[('blended', '���������'), ('online', '������'), ('offline', '�����')], default='blended', max_length=20)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cohort', models.CharField(help_text='��������: 2023', max_length=50)),
                ('study_group', models.CharField(max_length=50)),
                ('enrollment_year', models.PositiveIntegerField()),
                ('prior_gpa', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('learning_preferences', models.CharField(blank=True, max_length=255)),
                ('support_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('position', models.CharField(default='������', max_length=120)),
                ('research_focus', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('assessment_type', models.CharField(choices=[('quiz', '����'), ('project', '������'), ('exam', '�������'), ('lab', '������������')], max_length=20)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('weight', models.DecimalField(decimal_places=2, default=0.2, max_digits=4)),
                ('due_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='analytics_core.course')),
            ],
            options={
                'ordering': ['course__title', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='PedagogicalIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('strategy_type', models.CharField(choices=[('mentoring', '��������������'), ('adaptive', '���������� �������'), ('feedback', '����������� �������� �����'), ('peer', '��������������'), ('motivation', '������������� ���������')], max_length=20)),
                ('rationale', models.TextField()),
                ('recommended_actions', models.TextField()),
                ('expected_outcome', models.TextField()),
                ('priority', models.CharField(choices=[('high', '�������'), ('medium', '�������'), ('low', '������')], default='medium', max_length=20)),
                ('is_applied', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='analytics_core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='analytics_core.student')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_date', models.DateField()),
                ('status', models.CharField(choices=[('present', '�������������'), ('late', '�������'), ('absent', '������������')], max_length=20)),
                ('participation_score', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='analytics_core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='analytics_core.student')),
            ],
            options={
                'ordering': ['-lesson_date'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('submitted_at', models.DateTimeField()),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('feedback', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analytics_core.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='analytics_core.student')),
            ],
            options={
                'ordering': ['student__full_name', 'assessment__due_date'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='analytics_core.teacher'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_grade', models.PositiveIntegerField(default=85)),
                ('current_grade', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('progress_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('active', '�������'), ('support', '����� ���������'), ('completed', '��������')], default='active', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='analytics_core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='analytics_core.student')),
            ],
            options={
                'ordering': ['course__title', 'student__full_name'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='EngagementSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField()),
                ('platform_logins', models.PositiveIntegerField(default=0)),
                ('minutes_online', models.PositiveIntegerField(default=0)),
                ('forum_posts', models.PositiveIntegerField(default=0)),
                ('assignment_timeliness', models.DecimalField(decimal_places=2, default=1.0, help_text='���� ������������ ����������� ����� �� 0 �� 1.', max_digits=4)),
                ('self_regulation_score', models.PositiveIntegerField(default=50, help_text='������ ������� ��������������� 0-100')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_snapshots', to='analytics_core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_snapshots', to='analytics_core.student')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('student', 'course', 'week_start')},
            },
        ),
    ]
