# Generated by Django 6.0.4 on 2026-04-20 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('source_file', models.FileField(upload_to='analysis_uploads/')),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('sheet_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', '����'), ('processing', '??������'), ('ready', '�����'), ('failed', '?���')], default='draft', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('detected_columns', models.JSONField(blank=True, default=dict)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_name', models.CharField(max_length=180)),
                ('group_name', models.CharField(blank=True, max_length=120)),
                ('subject_name', models.CharField(blank=True, max_length=160)),
                ('lesson_topic', models.CharField(blank=True, max_length=200)),
                ('lesson_date', models.DateField(blank=True, null=True)),
                ('raw_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('attendance_status', models.CharField(choices=[('present', '?������'), ('late', '������'), ('absent', '?��������'), ('unknown', '������')], default='unknown', max_length=20)),
                ('performance_level', models.CharField(choices=[('low', '�?���'), ('medium', '������'), ('high', '��?���')], max_length=20)),
                ('source_row_number', models.PositiveIntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='analytics_core.analysisdataset')),
            ],
            options={
                'ordering': ['student_name', 'subject_name', 'lesson_date'],
            },
        ),
    ]
